### model
model_name_or_path: Qwen/Qwen3-VL-8B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
# lora_target: all
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj

### dataset
#dataset: aquarium-combined  # video: mllm_video_demo
template: qwen3_vl
cutoff_len: 2048
max_samples: 10000
max_steps: 800
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4
dataloader_pin_memory: true
dataloader_persistent_workers: true

### output
#output_dir: saves/qwen3vl-8b/lora/sft
logging_steps: 25
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
# num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
save_strategy: steps
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
